export const CityData = [
    {
        Type: 1,
        SolrID: '/tien-giang',
        ID: 1,
        Title: 'Tiền Giang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10549,
    },
    {
        Type: 1,
        SolrID: '/hung-yen',
        ID: 2,
        Title: 'Hưng Yên',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 11751,
    },
    {
        Type: 1,
        SolrID: '/ha-noi',
        ID: 3,
        Title: 'Hà Nội',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 271002,
    },
    {
        Type: 1,
        SolrID: '/tp-ho-chi-minh',
        ID: 4,
        Title: 'TP Hồ Chí Minh',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 449785,
    },
    {
        Type: 1,
        SolrID: '/ca-mau',
        ID: 5,
        Title: 'Cà Mau',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10632,
    },
    {
        Type: 1,
        SolrID: '/dac-lac',
        ID: 6,
        Title: 'Đắc Lắc',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 11112,
    },
    {
        Type: 1,
        SolrID: '/nam-dinh',
        ID: 7,
        Title: 'Nam Định',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 11761,
    },
    {
        Type: 1,
        SolrID: '/quang-ninh',
        ID: 8,
        Title: 'Quảng Ninh',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 19144,
    },
    {
        Type: 1,
        SolrID: '/dak-nong',
        ID: 9,
        Title: 'Đắk Nông',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 5234,
    },
    {
        Type: 1,
        SolrID: '/da-nang',
        ID: 10,
        Title: 'Đà Nẵng',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 39383,
    },
    {
        Type: 1,
        SolrID: '/hai-duong',
        ID: 11,
        Title: 'Hải Dương',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 16221,
    },
    {
        Type: 1,
        SolrID: '/long-an',
        ID: 12,
        Title: 'Long An',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 18465,
    },
    {
        Type: 1,
        SolrID: '/ben-tre',
        ID: 13,
        Title: 'Bến Tre',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 8079,
    },
    {
        Type: 1,
        SolrID: '/dong-thap',
        ID: 14,
        Title: 'Đồng Tháp',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10346,
    },
    {
        Type: 1,
        SolrID: '/vinh-long',
        ID: 15,
        Title: 'Vĩnh Long',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 7129,
    },
    {
        Type: 1,
        SolrID: '/kien-giang',
        ID: 16,
        Title: 'Kiên Giang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 16975,
    },
    {
        Type: 1,
        SolrID: '/tra-vinh',
        ID: 17,
        Title: 'Trà Vinh',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 5509,
    },
    {
        Type: 1,
        SolrID: '/soc-trang',
        ID: 18,
        Title: 'Sóc Trăng',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 6336,
    },
    {
        Type: 1,
        SolrID: '/bac-ninh',
        ID: 19,
        Title: 'Bắc Ninh',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 16792,
    },
    {
        Type: 1,
        SolrID: '/thanh-hoa',
        ID: 20,
        Title: 'Thanh Hoá',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 23341,
    },
    {
        Type: 1,
        SolrID: '/vung-tau',
        ID: 21,
        Title: 'Vũng Tàu',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 18491,
    },
    {
        Type: 1,
        SolrID: '/dong-nai',
        ID: 22,
        Title: 'Đồng Nai',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 40795,
    },
    {
        Type: 1,
        SolrID: '/binh-duong',
        ID: 23,
        Title: 'Bình Dương',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 42125,
    },
    {
        Type: 1,
        SolrID: '/thai-nguyen',
        ID: 24,
        Title: 'Thái Nguyên',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 9352,
    },
    {
        Type: 1,
        SolrID: '/thai-binh',
        ID: 25,
        Title: 'Thái Bình',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10604,
    },
    {
        Type: 1,
        SolrID: '/can-tho',
        ID: 26,
        Title: 'Cần Thơ',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 19151,
    },
    {
        Type: 1,
        SolrID: '/nghe-an',
        ID: 27,
        Title: 'Nghệ An',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 22465,
    },
    {
        Type: 1,
        SolrID: '/hue',
        ID: 28,
        Title: 'Huế',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 9884,
    },
    {
        Type: 1,
        SolrID: '/binh-phuoc',
        ID: 29,
        Title: 'Bình Phước',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10662,
    },
    {
        Type: 1,
        SolrID: '/quang-nam',
        ID: 30,
        Title: 'Quảng Nam',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 13554,
    },
    {
        Type: 1,
        SolrID: '/quang-ngai',
        ID: 31,
        Title: 'Quảng Ngãi',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10170,
    },
    {
        Type: 1,
        SolrID: '/ninh-thuan',
        ID: 32,
        Title: 'Ninh Thuận',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 4749,
    },
    {
        Type: 1,
        SolrID: '/lao-cai',
        ID: 33,
        Title: 'Lào Cai',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 6523,
    },
    {
        Type: 1,
        SolrID: '/hai-phong',
        ID: 34,
        Title: 'Hải Phòng',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 43526,
    },
    {
        Type: 1,
        SolrID: '/an-giang',
        ID: 35,
        Title: 'An Giang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 12732,
    },
    {
        Type: 1,
        SolrID: '/phu-tho',
        ID: 36,
        Title: 'Phú Thọ',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 9568,
    },
    {
        Type: 1,
        SolrID: '/tay-ninh',
        ID: 37,
        Title: 'Tây Ninh',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 11003,
    },
    {
        Type: 1,
        SolrID: '/khanh-hoa',
        ID: 38,
        Title: 'Khánh Hòa',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 21821,
    },
    {
        Type: 1,
        SolrID: '/phu-yen',
        ID: 39,
        Title: 'Phú Yên',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 6425,
    },
    {
        Type: 1,
        SolrID: '/hoa-binh',
        ID: 40,
        Title: 'Hòa Bình',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 6282,
    },
    {
        Type: 1,
        SolrID: '/tuyen-quang',
        ID: 41,
        Title: 'Tuyên Quang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 3652,
    },
    {
        Type: 1,
        SolrID: '/lai-chau',
        ID: 42,
        Title: 'Lai Châu',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 3057,
    },
    {
        Type: 1,
        SolrID: '/hau-giang',
        ID: 43,
        Title: 'Hậu Giang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 5457,
    },
    {
        Type: 1,
        SolrID: '/lam-dong',
        ID: 44,
        Title: 'Lâm Đồng',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 14964,
    },
    {
        Type: 1,
        SolrID: '/lang-son',
        ID: 45,
        Title: 'Lạng Sơn',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 5633,
    },
    {
        Type: 1,
        SolrID: '/ha-nam',
        ID: 46,
        Title: 'Hà Nam',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 6922,
    },
    {
        Type: 1,
        SolrID: '/bac-can',
        ID: 47,
        Title: 'Bắc Cạn',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 2325,
    },
    {
        Type: 1,
        SolrID: '/binh-dinh',
        ID: 48,
        Title: 'Bình Định',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 13804,
    },
    {
        Type: 1,
        SolrID: '/cao-bang',
        ID: 49,
        Title: 'Cao Bằng',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 3517,
    },
    {
        Type: 1,
        SolrID: '/son-la',
        ID: 50,
        Title: 'Sơn La',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 5303,
    },
    {
        Type: 1,
        SolrID: '/quang-binh',
        ID: 51,
        Title: 'Quảng Bình',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 8277,
    },
    {
        Type: 1,
        SolrID: '/quang-tri',
        ID: 52,
        Title: 'Quảng Trị',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 6854,
    },
    {
        Type: 1,
        SolrID: '/gia-lai',
        ID: 53,
        Title: 'Gia Lai',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 9341,
    },
    {
        Type: 1,
        SolrID: '/bac-giang',
        ID: 54,
        Title: 'Bắc Giang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 11333,
    },
    {
        Type: 1,
        SolrID: '/ha-tinh',
        ID: 55,
        Title: 'Hà Tĩnh',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 10510,
    },
    {
        Type: 1,
        SolrID: '/ninh-binh',
        ID: 56,
        Title: 'Ninh Bình',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 7725,
    },
    {
        Type: 1,
        SolrID: '/binh-thuan',
        ID: 57,
        Title: 'Bình Thuận',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 11056,
    },
    {
        Type: 1,
        SolrID: '/kon-tum',
        ID: 58,
        Title: 'Kon Tum',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 4639,
    },
    {
        Type: 1,
        SolrID: '/vinh-phuc',
        ID: 59,
        Title: 'Vĩnh Phúc',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 12496,
    },
    {
        Type: 1,
        SolrID: '/bac-lieu',
        ID: 60,
        Title: 'Bạc Liêu',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 5373,
    },
    {
        Type: 1,
        SolrID: '/yen-bai',
        ID: 61,
        Title: 'Yên Bái',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 4802,
    },
    {
        Type: 1,
        SolrID: '/dien-bien',
        ID: 62,
        Title: 'Điện Biên',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 3144,
    },
    {
        Type: 1,
        SolrID: '/ha-giang',
        ID: 63,
        Title: 'Hà Giang',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 4528,
    },
    {
        Type: 1,
        SolrID: '/chua-ro',
        ID: 64,
        Title: 'Chưa rõ',
        STT: 0,
        Created: null,
        Updated: null,
        TotalDoanhNghiep: 61822,
    },
];